## **Advance Operation with Business examples**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# Data Structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 15000, 16000, 27000, 18000], # Paradise Biryani 
    [2, 20000, 21000, 22000, 23000], # Beijing Bites
    [3, 25000, 26000, 17000, 28000], # Pizza Hub
    [4, 30000, 31000, 32000, 33000], # Burger King
    [5, 35000, 36000, 37000, 38000], # Taco Bell
])

In [12]:
# Find the shape

print('shape of sales_data:', sales_data.shape)

# Slicing the data 

print('sales_data:\n',sales_data[1:3])
print('sales_data:\n',sales_data[:,1:])

shape of sales_data: (5, 5)
sales_data:
 [[    2 20000 21000 22000 23000]
 [    3 25000 26000 17000 28000]]
sales_data:
 [[15000 16000 27000 18000]
 [20000 21000 22000 23000]
 [25000 26000 17000 28000]
 [30000 31000 32000 33000]
 [35000 36000 37000 38000]]


In [13]:
# Sum per year

print("=====Sum per year===== ")
print("2021:",np.sum(sales_data[:, 1:], axis=0))
print("2021:",np.sum(sales_data[:, 1:], axis=1)) # row wise per restaurant


=====Sum per year===== 
2021: [125000 130000 135000 140000]
2021: [ 76000  86000  96000 126000 146000]


In [14]:
# Average 

average_sales = np.mean(sales_data[:, 1:], axis=0)
print("=====Average Sales per Year=====")
print("2021:", average_sales)

=====Average Sales per Year=====
2021: [25000. 26000. 27000. 28000.]


Minmum sale 

In [17]:
# Minimum sale
min_sales = np.min(sales_data[:,1:], axis=0)
print("=====Minimum Sales per Restaurant=====")
print("Minimum Sales:", min_sales)

# MAximum sale
max_sales = np.max(sales_data[:,1:], axis=0)    
print("=====Maximum Sales per Restaurant=====")
print("Maximum Sales:", max_sales)

=====Minimum Sales per Restaurant=====
Minimum Sales: [15000 16000 17000 18000]
=====Maximum Sales per Restaurant=====
Maximum Sales: [35000 36000 37000 38000]
