### **import numpy**

In [1]:
import numpy as np

### **Creating Array**

In [5]:
array_01 = np.array([1,2,3,4,5])
print('Array one: ',array_01) 

array_02 = np.array([[1,2,3,4],[5,6,7,8]])
print('Array Two: ', array_02)

Array one:  [1 2 3 4 5]
Array Two:  [[1 2 3 4]
 [5 6 7 8]]


### **Python List vs Numpy Array**

In [ ]:
pyhton_list = [1,2,3,4,5]
print('Python List: ', pyhton_list * 2) 

numpy_array = np.array([1,2,3,4,5])
print('Numpy Array: ', numpy_array * 2)

Python List:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array:  [ 2  4  6  8 10]


### **Creating Array from Scratch**

In [6]:
zero = np.zeros((2,3))
print('Zero Array:\n ', zero, '\n') #Zero Array 

ones = np.ones((4,5))
print('ones Array:\n ', ones, '\n') #ones Array  | row by column

full = np.full((2,3), 7)
print('Full Array:\n ', full, '\n') #Full Array

random = np.random.random((3,4))
print('Random Array:\n ', random, '\n') #Random Array


sequence = np.arange(10, 40, 2)
print('Sequence Array:\n ', sequence, '\n') #Sequence Array


random_integer = np.random.randint(low = 0 , high = 40 , size = (3 , 5))
print("Random_integer List are \n" , random_integer , "\n" )



Zero Array:
  [[0. 0. 0.]
 [0. 0. 0.]] 

ones Array:
  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

Full Array:
  [[7 7 7]
 [7 7 7]] 

Random Array:
  [[0.32829378 0.5364333  0.89339454 0.48465188]
 [0.00133978 0.4762974  0.50757124 0.88538973]
 [0.96993685 0.41734202 0.84319685 0.39269502]] 

Sequence Array:
  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38] 

Random_integer List are 
 [[ 1 37 30 21 39]
 [ 3  6 35 27 26]
 [ 4 23 26 14 32]] 



### **Vector , Matrix , Tensor**

In [18]:
vector = np.array([1,2,3,4,5])
print('Vector:\n ', vector, '\n') #Vector

matrix = np.array([[1,2,3],[4,5,6]])
print('Matrix:\n ', matrix, '\n') #Matrix

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('Tensor:\n ', tensor, '\n') #Tensor

Vector:
  [1 2 3 4 5] 

Matrix:
  [[1 2 3]
 [4 5 6]] 

Tensor:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



## **Properties of Array**

In [8]:
array = np.array([[1,2,3,4],[5,6,7,8]])
array2 = np.array([[1,2,3,4],[5,6,7,8.6]])

print('Shapes of Array:', array.shape) #Shapes of Array
print('Data Type of Array:', array.dtype) #Data Type of Array
print('Data Type of Array:', array2.dtype) #Data Type of Array
print('Size of Array:', array.size) #Size of Array
print('Number of Dimensions:', array.ndim) #Number of Dimensions
print('Item Size:', array.itemsize) #Item Size


Shapes of Array: (2, 4)
Data Type of Array: int64
Data Type of Array: float64
Size of Array: 8
Number of Dimensions: 2
Item Size: 8


## **Reshaping Array**