### **import numpy**

In [ ]:
import numpy as np
import time

### **Creating Array**

In [5]:
array_01 = np.array([1,2,3,4,5])
print('Array one: ',array_01) 

array_02 = np.array([[1,2,3,4],[5,6,7,8]])
print('Array Two: ', array_02)

Array one:  [1 2 3 4 5]
Array Two:  [[1 2 3 4]
 [5 6 7 8]]


### **Python List vs Numpy Array**

In [ ]:
pyhton_list = [1,2,3,4,5]
print('Python List: ', pyhton_list * 2) 

numpy_array = np.array([1,2,3,4,5])
print('Numpy Array: ', numpy_array * 2)

Python List:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array:  [ 2  4  6  8 10]


### **Creating Array from Scratch**

In [ ]:
zero = np.zeros((2,3))
print('Zero Array:\n ', zero) #Zero Array 

ones = np.ones((4,5))
print('ones Array:\n ', ones) #ones Array  | row by column

full = np.full((2,3), 7)
print('Full Array:\n ', full) #Full Array

random = np.random.random((3,4))
print('Random Array:\n ', random) #Random Array


sequence = np.arange(10, 20, 2)
print('Sequence Array:\n ', sequence) #Sequence Array

Zero Array:
  [[0. 0. 0.]
 [0. 0. 0.]]
ones Array:
  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array:
  [[7 7 7]
 [7 7 7]]
Random Array:
  [[0.26594651 0.94343445 0.02497504 0.07212937]
 [0.16310276 0.61069261 0.39413886 0.30302896]
 [0.24915603 0.6542941  0.93686413 0.04697041]]
