In [1]:
import numpy as np 

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

array1 = np.arange(12)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## **Numpy Operations**

### Slicing and Indexing 

In [ ]:
print(array[0:5])  # Slicing the first 5 elements
print(array1[5:10])  
print(array)

print('Slicing with steping',array[2:8:2])
print('slicing with negative value', array1[-4])

[1 2 3 4 5]
[5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
Slicing with steping [3 5 7]
slicing with negaive value 8


In [ ]:
array_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2D_array: ', array_2d)

#speciifc indexing 

print('2D_array indexing',array_2d[1,2])

print('entire row', array_2d[1])  # Entire second row
print('entire column;', array_2d[:,4])  # Entire second column

2D_array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2D_array indexing 8
entire row [ 6  7  8  9 10]
entire column; [ 5 10]


## **Sorting Array**

In [31]:
array_sorted = np.array([5,2,9,1,5,6])
print('Sorted array',np.sort(array_sorted))

array_sorted_2d= np.array([[9,3],[2,9],[8,6]])
print('2D Sorted array',np.sort(array_sorted_2d, axis=0)) 
print('2D Sorted array by row ',np.sort(array_sorted_2d, axis=1)) 

Sorted array [1 2 5 5 6 9]
2D Sorted array [[2 3]
 [8 6]
 [9 9]]
2D Sorted array by row  [[3 9]
 [2 9]
 [6 8]]
