In [1]:
import numpy as np 

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

array1 = np.arange(12)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## **Numpy Operations**

### Slicing and Indexing 

In [ ]:
print(array[0:5])  # Slicing the first 5 elements
print(array1[5:10])  
print(array)

print('Slicing with steping',array[2:8:2])
print('slicing with negative value', array1[-4])

[1 2 3 4 5]
[5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
Slicing with steping [3 5 7]
slicing with negaive value 8


In [13]:
array_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2D_array: ', array_2d)

2D_array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
