### **import numpy**

In [ ]:
import numpy as np
import time

### **Creating Array**

In [5]:
array_01 = np.array([1,2,3,4,5])
print('Array one: ',array_01) 

array_02 = np.array([[1,2,3,4],[5,6,7,8]])
print('Array Two: ', array_02)

Array one:  [1 2 3 4 5]
Array Two:  [[1 2 3 4]
 [5 6 7 8]]


### **Python List vs Numpy Array**

In [ ]:
pyhton_list = [1,2,3,4,5]
print('Python List: ', pyhton_list * 2) 

numpy_array = np.array([1,2,3,4,5])
print('Numpy Array: ', numpy_array * 2)

Python List:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array:  [ 2  4  6  8 10]


### **Creating Array from Scratch**

In [16]:
zero = np.zeros((2,3))
print('Zero Array:\n ', zero) #Zero Array 

ones = np.ones((4,5))
print('ones Array:\n ', ones) #ones Array  | row by column

full = np.full((2,3), 7)
print('Full Array:\n ', full) #Full Array

random = np.random.random((3,4))
print('Random Array:\n ', random) #Random Array


sequence = np.arange(10, 40, 2)
print('Sequence Array:\n ', sequence) #Sequence Array


random_integer = np.random.randint(low = 0 , high = 40 , size = (3 , 5))
print("Random_integer List are \n" , random_integer , "\n" )

Zero Array:
  [[0. 0. 0.]
 [0. 0. 0.]]
ones Array:
  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array:
  [[7 7 7]
 [7 7 7]]
Random Array:
  [[0.00955839 0.71161409 0.50215423 0.76827736]
 [0.42323273 0.60096358 0.42080593 0.5206319 ]
 [0.8312048  0.89073321 0.68010242 0.56910845]]
Sequence Array:
  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


Random_integer List are 
 [[16 18 10  7  3]
 [12 25 13 11  2]
 [16  9 39 11 11]] 

