### **import numpy**

In [2]:
import numpy as np

### **Creating Array**

In [ ]:
array_01 = np.array([1,2,3,4,5])
print('Array one: ',array_01) 

array_02 = np.array([[1,2,3,4],[5,6,7,8]])
print('Array Two: ' array_02)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
